//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSchoolManagementSystem.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class School_Management_SystemEntities : DbContext
    {
        public School_Management_SystemEntities()
            : base("name=School_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Standards> tbl_Standards { get; set; }
        public virtual DbSet<tbl_Teachers> tbl_Teachers { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
    
        public virtual ObjectResult<SP_GetallStandards_Result> SP_GetallStandards()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetallStandards_Result>("SP_GetallStandards");
        }
    
        public virtual ObjectResult<SP_GetallTeachersRecords_Result> SP_GetallTeachersRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetallTeachersRecords_Result>("SP_GetallTeachersRecords");
        }
    }
}
